//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientServiceImage
    {
        public int ClientServiceImageId { get; set; }
        public int ClientServiceId { get; set; }
        public byte[] Image { get; set; }
    
        public virtual ClientService ClientService { get; set; }
    }
}
