//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceImage
    {
        public int ServiceImageId { get; set; }
        public int ServiceId { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
