//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ClientDetails
    {
        public int Идентификатор { get; set; }
        public string ФИО { get; set; }
        public string Телефон { get; set; }
        public string Email { get; set; }
        public System.DateTime ДатаРождения { get; set; }
        public System.DateTime ДатаРегистрации { get; set; }
        public Nullable<int> Возраст { get; set; }
        public Nullable<int> КоличествоПосещений { get; set; }
        public Nullable<int> КоличествоТегов { get; set; }
        public string Пол { get; set; }
        public Nullable<System.DateTime> ДатаПоследнегоПосещения { get; set; }
    }
}
